# Generated by Django 4.2.7 on 2025-06-12 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
