# Generated by Django 4.2.7 on 2025-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='package_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
